spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://plogging-db.cdvumpepcdrw.ap-northeast-2.rds.amazonaws.com/dev_ploggingdb?autoReconnect=true
    username: admin
    password: Pplogging1234!

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true