spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ploggingrds2.cdvumpepcdrw.ap-northeast-2.rds.amazonaws.com:3306/ploggingdb
    username: admin
    password: Pplogging123!!

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  jwt:
    access-key: ploggingaccesskey1234!!@
    refresh-key: ploggingrefreshkey1234!!@

cloud:
  aws:
    s3:
      bucket: buketName
    credentials:
      accesskey: AKVABMA6U2IKIL4R3R7E
      secretkey: kciHJGlpupjKPnjkEU7/pp9R+cOFdvKu9McFp2cc
    region:
      static: ap-northeast-2
    stack:
      auto: false

sms:
  service-id: ncp:sms:kr:280044915694:infra-sms
  access-key: JUARhMRAzpFrstZqd775
  secret-key: lgiOpHwGvTW5HjcIaCKkhATBHFB3qeRuWzaBOrZZ
  phone-num: 0318488224